# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'zima-nas'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus-zima'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
         - targets: ['localhost:9090']
           labels:
             host: "zima"

  - job_name: 'cadvisor-zima'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          host: "zima"

  - job_name: 'node-exporter-zima'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
  
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          host: "zima"

            #  - job_name: 'prometheus'
            #
    # Override the global default and scrape targets from this job every 5 seconds.
    #    scrape_interval: 15s

            #    static_configs:
            #         - targets: ['192.168.0.81:9090']
            #           labels:
            #             host: "delphi"

  - job_name: 'cadvisor-delphi'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
      - targets: ['192.168.0.81:8080']
        labels:
          host: "delphi"

  - job_name: 'node-exporter-delphi'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
      - targets: ['192.168.0.81:9100']
        labels: 
          host: "delphi"

  - job_name: 'mqtt-exporter-zima'

    scrape_interval: 15s

    static_configs:
      - targets: ["mqtt-exporter:9000"]
        labels:
          host: "zima"

  - job_name: 'internet-monitoring-zima'

    scrape_interval: 10m
    scrape_timeout: 60s # running speedtest needs time to complete

    static_configs:
      - targets: ['speedtest:9798']
        labels:
          host: "zima"

  - job_name: 'daiken-monitoring-zima'

    scrape_interval: 5m

    static_configs:
      - targets: ['daikin-prometheus-exporter:5555']
        labels:
          host: "zima"

  
  - job_name: 'octoprint-monitoring-octopi'
                
    scrape_interval: 15s
    metrics_path: '/plugin/prometheus_exporter/metrics'
    params:
        apikey: ['6C959C68FCD1476EA596F934EE58FCDE']
    static_configs:
      - targets: ['192.168.0.35:80']
        labels:
          host: "octopi"

  - job_name: 'node-exporter-octopi'

    scrape_interval: 15s

    static_configs:
      - targets: ['192.168.0.35:9100']
        labels:
          host: "octopi"

  - job_name: 'cadvisor-octopi'

    scrape_interval: 15s

    static_configs:
      - targets: ['192.168.0.35:8080']
        labels:
          host: "octopi"
