{
 "title": "Environment Monitoring",
 "description": "Environment Monitoring  - Temperature, Humidity, CO2, PM2.5, TVOC",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Rooms",
    "query": "office, kitchen, Louise_Room, Everett_Room, bedroom"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<span style=\"font-size:34px\">Temperature</span>\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mqtt_temperature{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    },
    { "expr": "ac_tempIndoor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average House Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "mqtt_temperature{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    },
    { "expr": "ac_tempIndoor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "mqtt_temperature{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    },
    { "expr": "ac_tempIndoor", "legendFormat": "__auto" },
    { "expr": "ac_tempOutdoor", "legendFormat": "__auto" },
    { "expr": "ac_heatingStatus >= 2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Highest Temperature",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "mqtt_temperature{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    },
    { "expr": "ac_tempIndoor", "legendFormat": "__auto" },
    { "expr": "ac_tempOutdoor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lowest Temperature",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "mqtt_temperature{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    },
    { "expr": "ac_tempIndoor", "legendFormat": "__auto" },
    { "expr": "ac_tempOutdoor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqtt_temperature{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    },
    { "expr": "ac_tempIndoor", "legendFormat": "__auto" },
    { "expr": "ac_tempOutdoor", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "<span style=\"font-size:34px\">Humidity</span>\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mqtt_humidity{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    },
    { "expr": "ac_humIndoor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average House Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "mqtt_humidity{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 18, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "mqtt_humidity{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    },
    { "expr": "ac_humIndoor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Highest Humidity",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "mqtt_humidity{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    },
    { "expr": "ac_humIndoor", "legendFormat": "__auto" },
    { "expr": "ac_humidity_outside", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lowest Humidity",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "mqtt_humidity{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    },
    { "expr": "ac_humIndoor", "legendFormat": "__auto" },
    { "expr": "ac_humidity_outside", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Humidity",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 22, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqtt_humidity{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    },
    { "expr": "ac_humIndoor", "legendFormat": "__auto" },
    { "expr": "ac_humidity_outside", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
   "options": {
    "content": "<span style=\"font-size:34px\">CO2</span>\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mqtt_CO2{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average House CO2 Concentration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_CO2{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO2 Concentrations",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 18, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "mqtt_CO2{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest CO2",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 18, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "mqtt_CO2{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lowest CO2",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 20, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "mqtt_CO2{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CO2",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 22, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqtt_CO2{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 },
   "options": {
    "content": "<span style=\"font-size:34px\">PM2.5</span>\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mqtt_pm25{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average House PM2.5 Concentration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_pm25{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PM2.5 Concentrations",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 18, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "mqtt_pm25{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest PM2.5",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 18, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "mqtt_pm25{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lowest PM2.5",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 20, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "mqtt_pm25{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CO2",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 22, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mqtt_pm25{topic=~\"device_${Rooms}_sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}