{
 "title": "Linux memory",
 "description": "This dashboard details memory area's as seen in linux' /proc/meminfo together with swap information. This allows you to get an overview of actual current usage.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Linux memory distribution",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes-node_memory_MemFree_bytes-node_memory_KernelStack_bytes-node_memory_AnonPages_bytes-node_memory_PageTables_bytes-node_memory_Slab_bytes-node_memory_Cached_bytes-node_memory_SwapCached_bytes-node_memory_Buffers_bytes-(node_memory_HugePages_Total*2097152)",
     "legendFormat": "Unaccounted For"
    },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    { "expr": "node_memory_SwapCached_bytes", "legendFormat": "Swap Cached" },
    { "expr": "node_memory_KernelStack_bytes", "legendFormat": "Kernel Stack" },
    { "expr": "node_memory_Slab_bytes", "legendFormat": "Slab" },
    { "expr": "node_memory_PageTables_bytes", "legendFormat": "Page Tables" },
    { "expr": "node_memory_AnonPages_bytes", "legendFormat": "Anonymous" },
    { "expr": "node_memory_Shmem_bytes", "legendFormat": "Shared memory smallpages" },
    {
     "expr": "node_memory_Cached_bytes-node_memory_Shmem_bytes",
     "legendFormat": "Mapped and Cached"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    {
     "expr": "(node_memory_HugePages_Free-node_memory_HugePages_Rsvd)*2097152",
     "legendFormat": "Hugepages Free"
    },
    {
     "expr": "node_memory_HugePages_Rsvd*2097152",
     "legendFormat": "Hugepages Reserved"
    },
    {
     "expr": "(node_memory_HugePages_Total-node_memory_HugePages_Free)*2097152",
     "legendFormat": "Hugepages Used"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "Free" },
    {
     "expr": "node_memory_SwapTotal_bytes-node_memory_SwapFree_bytes",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Swapping",
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "increase(node_vmstat_pswpin[5s])",
     "legendFormat": "Swap in pages"
    },
    {
     "expr": "increase(node_vmstat_pswpout[5s])",
     "legendFormat": "Swap out pages"
    }
   ]
  }
 ]
}