{
 "title": "Speedtest",
 "description": "Speedtest metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ISP",
    "label": "ISP",
    "query": {
     "query": "label_values(speedtest_latency_seconds, user_isp)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "avg(speedtest_download_bits_per_second{user_isp=\"$ISP\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "avg(speedtest_upload_bits_per_second{user_isp=\"$ISP\"})",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Lastest Results",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{user_isp=\"$ISP\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second{user_isp=\"$ISP\"}",
     "legendFormat": "Upload"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_download_bits_per_second{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_download_bits_per_second{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_download_bits_per_second[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(speedtest_upload_bits_per_second{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "min(min_over_time(speedtest_upload_bits_per_second{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_upload_bits_per_second[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(speedtest_ping_latency_milliseconds{user_isp=\"$ISP\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(speedtest_ping_latency_milliseconds{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "max(max_over_time(speedtest_ping_latency_milliseconds{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_ping_latency_milliseconds[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(speedtest_jitter_latency_milliseconds{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Best"
    },
    {
     "expr": "max(max_over_time(speedtest_jitter_latency_milliseconds{user_isp=\"$ISP\"}[1w:5m]))",
     "legendFormat": "Worst"
    },
    {
     "expr": "avg(avg_over_time(speedtest_jitter_latency_milliseconds[1w:5m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(speedtest_jitter_latency_milliseconds{user_isp=\"$ISP\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "avg(process_cpu_seconds_total)", "legendFormat": "Duration" }
   ]
  },
  {
   "title": "Test Results",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second"
    },
    {
     "expr": "speedtest_upload_bits_per_second"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}